---
title: "p8105_hw2_nec2159"
author: "Nicole Criscuolo"
date: "2025-09-23"
output: github_document
---

```{r echo = FALSE, message = FALSE}
library(tidyverse)
library(dplyr)
library(readxl)
```
 
## Problem 1

```{r}
pols_df =
  read_csv("data/pols-month.csv") |> 
  relocate(mon, prez_gop, prez_dem) |> 
  separate(mon, into = c("year", "month", "day"), sep = "-") |> 
  mutate(month = month.name[as.numeric(month)]) |> 
  pivot_longer(
    cols = prez_gop:prez_dem,
    names_to = "president",
    values_to = "yes_no"
  )|> 
  filter(yes_no != 0) |> 
    mutate(president = case_match(
    president,
    "prez_dem" ~ "dem",
    "prez_gop" ~ "gop"
  )) |> 
  select(-day, -yes_no) |> 
  mutate(year = as.numeric(year))
```

```{r}
snp_df = 
  read_csv("data/snp.csv") |> 
  separate(date, into = c("month", "day", "year"), sep = "/") |> 
  mutate(year = as.numeric(year), 
         year = if_else(year >= 50, year + 1900, year + 2000),
         month = as.numeric(month)) |> 
  arrange(year, month) |> 
  mutate(month = month.name[month]) |> 
  relocate(year) |> 
  select(-day)
```
  
```{r}
unemployment_df =
  read_csv("data/unemployment.csv") |> 
  pivot_longer(
    cols = Jan:Dec,
    names_to = "month",
    values_to = "percentage"
  ) |> 
  rename(year = Year) |> 
  mutate(month = case_match(
    month,
    "Jan" ~ "January",
    "Feb" ~ "February",
    "Mar" ~ "March",
    "Apr" ~ "April",
    "May" ~ "May",
    "Jun" ~ "June",
    "Jul" ~ "July",
    "Aug" ~ "August",
    "Sep" ~ "September",
    "Oct" ~ "October",
    "Nov" ~ "November",
    "Dec" ~ "December",
  )) |> 
  mutate(year = as.numeric(year))
```

```{r}
joined_df = 
  full_join(pols_df, snp_df)
all_df = 
  full_join(joined_df, unemployment_df)
```

## Problem 2

```{r}
mr_trash_df =
  read_excel("data/202409 Trash Wheel Collection Data.xlsx", 
            skip = 1, 
            na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  select(-x15, -x16) |> 
  drop_na(dumpster) |> 
  mutate(sports_balls = as.integer(round(sports_balls)),
         year = as.numeric(year),
         wheel = "mister")

# do i also need to separate date into month day year columns
```

```{r}
prof_trash_df =
  read_excel("data/202409 Trash Wheel Collection Data.xlsx", 
             sheet = 2,
             skip = 1,
             na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(year = as.numeric(year),
         wheel = "professor")
```

```{r}
gwynnda_trash_df =
  read_excel("data/202409 Trash Wheel Collection Data.xlsx",
             sheet = 4,
             skip = 1,
             na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(year= as.numeric(year),
         wheel = "gwynnda")
```

```{r}
trash_df = 
  full_join(mr_trash_df, prof_trash_df)
full_trash_df =
  full_join(trash_df, gwynnda_trash_df) |> 
  relocate(wheel)
```

## Problem 3
```{r}
zip_df =
  read_csv("data/Zip Codes.csv", na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  select(-state_fips, -file_date, -county)

zori_df =
  read_csv("data/Zip_zori_NYC.csv", na = c("NA", ".", "")) |> 
  pivot_longer(
    cols = "2015-01-31":"2024-08-31",
    names_to = "date",
    values_to = "zori"
  ) |> 
  janitor::clean_names() |> 
  rename(zip_code = region_name) |> 
  select(-region_type, -state_name, -state, -city, -metro)
```

```{r}
zip_zori_df =
  full_join(zip_df, zori_df) |>
  relocate(county_name, neighborhood)
```
```{r}
missing_zips_df =
  anti_join(zip_df, zori_df)
```

